PrestigeYoYo/src/Web/Controllers/ScheduleController.cs
/// Scheduling controller
/// Codeora 2012
///

namespace Prestige.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using AutoMapper;
    using Prestige.DB.Models;
    using Prestige.Services;

    /// <summary>
    /// The scheduling controller.
    /// </summary>
    public class ScheduleController : PrestigeController
    {
        /// <summary>
        /// Initializes a new instance of the
        /// <see cref="ScheduleController" /> class.
        /// </summary>
        /// <param name="scheduleService">The schedule service.</param>
        public ScheduleController(
                    IMappingEngine mapper,
                    IScheduleService scheduleService,
                    IProductService productService,
                    IUserService userService) : base(mapper)
        {
            if (scheduleService == null)
            {
                throw new ArgumentNullException("scheduleService");
            }
            else if (productService == null)
            {
                throw new ArgumentNullException("productService");
            }
            else if (userService == null)
            {
                throw new ArgumentNullException("userService");
            }

            this.ScheduleService = scheduleService;
            this.ProductService = productService;
            this.UserService = userService;
        }

        /// <summary>
        /// Gets or sets the service.
        /// </summary>
        /// <value>
        /// The service.
        /// </value>
        private IScheduleService ScheduleService { get; set; }

        /// <summary>
        /// Gets or sets the product service.
        /// </summary>
        /// <value>
        /// The product service.
        /// </value>
        private IProductService ProductService { get; set; }

        /// <summary>
        /// Gets or sets the user service.
        /// </summary>
        /// <value>
        /// The user service.
        /// </value>
        private IUserService UserService { get; set; }

        /// <summary>
        /// Get the index view.
        /// </summary>
        /// <returns>The index view.</returns>
        public ActionResult Index()
        {
            var schedule = this.ScheduleService.List().Where(s => s.Product != null).ToArray();
            var products = this.ProductService.List().OrderBy(p => p.SKU).ToArray();
            ViewBag.Title = "Product Scheduling";
            return View(
                new Tuple<
                    IEnumerable<Schedule>,
                    IEnumerable<Product>>(
                        schedule,
                        products));
        }

        /// <summary>
        /// Editors this instance.
        /// </summary>
        /// <returns>The editor view.</returns>
        public ActionResult Editor(Product[] products)
        {
            var user = this.User.Identity.Name as string;

            if (this.UserService.IsUserInRole(user, "Administrator"))
            {
                //var products = this.ProductService.List().OrderBy(p => p.SKU).ToArray();
                return PartialView(products);
            }

            return new EmptyResult();
        }

        /// <summary>
        /// Edits the specified day/time schedule.
        /// </summary>
        /// <param name="day">The day.</param>
        /// <param name="start">The start.</param>
        /// <param name="finish">The finish.</param>
        /// <param name="product">The product.</param>
        /// <returns>Redirect to the index action.</returns>
        [HttpPost]
        public ActionResult Edit(string day, int start, int finish, Guid? product)
        {
            try
            {
                var prod = this.ProductService.List()
                                    .FirstOrDefault(p => p.Id == product);

                this.ScheduleService.Add(day, start, finish, prod);
            }
            catch (ArgumentException)
            {
                // woohoo!
            }

            return RedirectToAction("Index");
        }
    }
}

PrestigeYoYo/src/Web/Views/Schedule/Editor.cshtml
@model IEnumerable<Prestige.DB.Models.Product>
    
<script type="text/javascript">
    $(function () {
        $("button").button().click(function () {
            var day = $("#day option:selected").text();
            var start = $("#start option:selected").text();
            var finish = $("#finish option:selected").text();
            var product = $("#product option:selected").text();

            if (validate(start, finish)) {
                var msg = "Schedule " + product + "<br />from " + start + " to " + finish + " on " + day + "?";
                $("#dialog-message").html(msg);
                $("#dialog-confirm").dialog({
                    resizable: false,
                    height: 160,
                    width: 350,
                    modal: true,
                    buttons: {
                        Schedule: function () {
                            $("#scheduleForm").submit();
                        },
                        Cancel: function () {
                            $(this).dialog("close");
                        }
                    }
                });
            }
        });
    });

    function validate(start, finish) {
        var msg;
        if (start >= finish) {
            msg = "The finish time must come after the start time.";
        }

        if (msg) {
            $("#error-message").html(msg);
            $("#dialog-error").dialog({
                resizable: false,
                height: 160,
                width: 350,
                modal: true,
                buttons: {
                    Close: function () {
                        $(this).dialog("close");
                    }
                }
            });
            return false;
        }

        return true;
    }
</script>
           
@using (Html.BeginForm("Edit", "Schedule", FormMethod.Post, new Dictionary<string, object>() { { "id", "scheduleForm" } }))
{
<div style="border:2px solid black;text-align:center;">
    <div style="display:inline-block;">
        <span class="dropdown-text">Day:</span>
        <select id="day" name="day" class="dropdown" style="width:120px;">
            <option value="SUNDAY">Sunday</option>
            <option value="MONDAY" selected="selected">Monday</option>
            <option value="TUESDAY">Tuesday</option>
            <option value="WEDNESDAY">Wednesday</option>
            <option value="THURSDAY">Thursday</option>
            <option value="FRIDAY">Friday</option>
            <option value="SATURDAY">Saturday</option>
        </select>
    </div>
    <div style="display:inline-block;">
        <span class="dropdown-text">Start:</span>
        <select id="start" name="start" class="dropdown" style="width:80px;">
            <option value="0">00:00</option>
            <option value="1">01:00</option>
            <option value="2">02:00</option>
            <option value="3">03:00</option>
            <option value="4">04:00</option>
            <option value="5">05:00</option>
            <option value="6">06:00</option>
            <option value="7">07:00</option>
            <option value="8">08:00</option>
            <option value="9">09:00</option>
            <option value="10">10:00</option>
            <option value="11">11:00</option>
            <option value="12">12:00</option>
            <option value="13">13:00</option>
            <option value="14">14:00</option>
            <option value="15">15:00</option>
            <option value="16">16:00</option>
            <option value="17">17:00</option>
            <option value="18">18:00</option>
            <option value="19">19:00</option>
            <option value="20">20:00</option>
            <option value="21">21:00</option>
            <option value="22">22:00</option>
            <option value="23">23:00</option>
        </select>
    </div>
    <div style="display:inline-block;">
        <span class="dropdown-text">Finish:</span>
        <select id="finish" name="finish" class="dropdown" style="width:80px;">
            <option value="1">01:00</option>
            <option value="2">02:00</option>
            <option value="3">03:00</option>
            <option value="4">04:00</option>
            <option value="5">05:00</option>
            <option value="6">06:00</option>
            <option value="7">07:00</option>
            <option value="8">08:00</option>
            <option value="9">09:00</option>
            <option value="10">10:00</option>
            <option value="11">11:00</option>
            <option value="12">12:00</option>
            <option value="13">13:00</option>
            <option value="14">14:00</option>
            <option value="15">15:00</option>
            <option value="16">16:00</option>
            <option value="17">17:00</option>
            <option value="18">18:00</option>
            <option value="19">19:00</option>
            <option value="20">20:00</option>
            <option value="21">21:00</option>
            <option value="22">22:00</option>
            <option value="23">23:00</option>
            <option value="24">24:00</option>
        </select>
    </div>
    <div style="display:inline-block;">
        <span class="dropdown-text">Product:</span>
        <select id="product" name="product" class="dropdown" style="width:250px;">
            <option value=""><i>[None]</i></option>
        @foreach (var product in Model)
        {
            <option class="c@(product.Id.ToString())" value="@product.Id.ToString()">@string.Format("{0} ({1})", product.Description, product.SKU)</option>
        }
        </select>
    </div>
    <button style="width:140px;margin-left:30px;" type="button">Schedule</button>
</div>
}

<div id="dialog-confirm" title="Confirm Schedule Change">
    <span id="dialog-message"></span>
</div>

<div id="dialog-error" title="Scheduling Error">
    <span id="error-message" style="color:Red"></span>
</div>

PrestigeYoYo/src/Web/Views/Schedule/Index.cshtml
@using Prestige.DB.Models;
@model Tuple<IEnumerable<Schedule>, IEnumerable<Product>>

@{
    var monday = Model.Item1.Where(s => s.Day == "MONDAY");
    var tuesday = Model.Item1.Where(s => s.Day == "TUESDAY");
    var wednesday = Model.Item1.Where(s => s.Day == "WEDNESDAY");
    var thursday = Model.Item1.Where(s => s.Day == "THURSDAY");
    var friday = Model.Item1.Where(s => s.Day == "FRIDAY");
    var saturday = Model.Item1.Where(s => s.Day == "SATURDAY");
    var sunday = Model.Item1.Where(s => s.Day == "SUNDAY");

    Product lastMon = null;
    Product lastTue = null;
    Product lastWed = null;
    Product lastThur = null;
    Product lastFri = null;
    Product lastSat = null;
    Product lastSun = null;

    var colors = new string[]
    {
        "#ED1C24",
        "#F7941D",
        "#8DC73F",
        "#00A651",
        "#00AEEF",
        "#0054A6",
        "#662D91",
        "#EC008C",
        "#F26522",
        "#FFF200",
        "#39B54A",
        "#00A99D",
        "#0072BC",
        "#2E3192",
        "#92278F",
        "#ED145B",
    };
}

<style type="text/css">
    .time-col
    {
        width:70px;
        text-align:center;
    }
    .off-time
    {
        background:White;
    }
    .dropdown
    {
        margin:20px 10px 20px 10px;
    }
    .dropdown-text
    {
        width:70px;
        margin:20px 10px 5px 10px;
        text-align:right;
        display:inline-block;
    }
@{ int c = 0; }
@foreach (var guid in Model.Item2.Select(p => p.Id))
{
    @(".c" + guid.ToString() + " { background-color:" + colors[(c++ % colors.Length)] + ";color:black; }\r\n" )
}
</style>

<table style="table-layout:fixed;width:100%;">
    <tr>
        <td class="time-col"></td>
        <td style="text-align:center;"><strong>Sunday</strong></td>
        <td style="text-align:center"><strong>Monday</strong></td>
        <td style="text-align:center"><strong>Tuesday</strong></td>
        <td style="text-align:center"><strong>Wednesday</strong></td>
        <td style="text-align:center"><strong>Thursday</strong></td>
        <td style="text-align:center"><strong>Friday</strong></td>
        <td style="text-align:center"><strong>Saturday</strong></td>
        <td class="time-col" style="text-align:right"></td>
    </tr>
</table>

<table style="table-layout:fixed;width:100%;" border="1">
@for (int i = 0; i < 24; i++)
{    
    var mon = monday.FirstOrDefault(s => s.Hour == i);
    var tue = tuesday.FirstOrDefault(s => s.Hour == i);
    var wed = wednesday.FirstOrDefault(s => s.Hour == i);
    var thur = thursday.FirstOrDefault(s => s.Hour == i);
    var fri = friday.FirstOrDefault(s => s.Hour == i);
    var sat = saturday.FirstOrDefault(s => s.Hour == i);
    var sun = sunday.FirstOrDefault(s => s.Hour == i);
    
    <tr>
        <td class="time-col">@string.Format("{0:D2}:00", i)</td>
        <td class="@(sun == null ? "off-time" : "c" + sun.Product.Id.ToString())">
            @(sun != null && sun.Product != lastSun ? string.Format("{0} ({1})", sun.Product.Description, sun.Product.SKU) : "")
        </td>
        <td class="@(mon == null ? "off-time" : "c" + mon.Product.Id.ToString())">
            @(mon != null && mon.Product != lastMon ? string.Format("{0} ({1})", mon.Product.Description, mon.Product.SKU) : "")
        </td>
        <td class="@(tue == null ? "off-time" : "c" + tue.Product.Id.ToString())">
            @(tue != null && tue.Product != lastTue ? string.Format("{0} ({1})", tue.Product.Description, tue.Product.SKU) : "")
        </td>
        <td class="@(wed == null ? "off-time" : "c" + wed.Product.Id.ToString())">
            @(wed != null && wed.Product != lastWed ? string.Format("{0} ({1})", wed.Product.Description, wed.Product.SKU) : "")
        </td>
        <td class="@(thur == null ? "off-time" : "c" + thur.Product.Id.ToString())">
            @(thur != null && thur.Product != lastThur ? string.Format("{0} ({1})", thur.Product.Description, thur.Product.SKU) : "")
        </td>
        <td class="@(fri == null ? "off-time" : "c" + fri.Product.Id.ToString())">
            @(fri != null && fri.Product != lastFri ? string.Format("{0} ({1})", fri.Product.Description, fri.Product.SKU) : "")
        </td>
        <td class="@(sat == null ? "off-time" : "c" + sat.Product.Id.ToString())">
            @(sat != null && sat.Product != lastSat ? string.Format("{0} ({1})", sat.Product.Description, sat.Product.SKU) : "")
        </td>
        <td class="time-col">@string.Format("{0:D2}:00", i)</td>
    </tr>
    
    lastSun = sun == null ? null : sun.Product;
    lastMon = mon == null ? null : mon.Product;
    lastTue = tue == null ? null : tue.Product;
    lastWed = wed == null ? null : wed.Product;
    lastThur = thur == null ? null : thur.Product;
    lastFri = fri == null ? null : fri.Product;
    lastSat = sat == null ? null : sat.Product;
}
</table>
<br />

@Html.Action("Editor", "Schedule", new { products = Model.Item2 })