PrestigeYoYo/src/Web/Controllers/ReportController.cs
/// Reporting controller
/// Codeora 2012
///

namespace Prestige.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Linq;
    using System.Text;
    using System.Web.Mvc;
    using AutoMapper;
    using DotNet.Highcharts;
    using DotNet.Highcharts.Enums;
    using DotNet.Highcharts.Helpers;
    using DotNet.Highcharts.Options;
    using Prestige.DB.Models;
    using Prestige.Services;
    using Prestige.ViewModels;
    using System.Collections.ObjectModel;

    /// <summary>
    /// Class for managing Home requests.
    /// </summary>
    public class ReportController : PrestigeController
    {
        /// <summary>
        /// Initializes a new instance of the
        /// <see cref="HomeController" /> class.
        /// </summary>
        /// <param name="mapper">The mapper.</param>
        /// <param name="productService">The product service.</param>
        public ReportController(
                IMappingEngine mapper,
                IProductService productService,
                IProductionStageService productionStageService,
                IProductionStationService stationService)
            : base(mapper)
        {
            if (productService == null)
            {
                throw new ArgumentNullException("productService");
            }
            else if (productionStageService == null)
            {
                throw new ArgumentNullException("productionStageService");
            }
            else if (stationService == null)
            {
                throw new ArgumentNullException("stationService");
            }

            this.ProductService = productService;
            this.ProductionStageService = productionStageService;
            this.StationService = stationService;
        }

        /// <summary>
        /// Gets or sets the product service.
        /// </summary>
        /// <value>
        /// The product service.
        /// </value>
        private IProductService ProductService { get; set; }

        /// <summary>
        /// Gets or sets the production stage service.
        /// </summary>
        /// <value>
        /// The production stage service.
        /// </value>
        private IProductionStageService ProductionStageService { get; set; }

        /// <summary>
        /// Gets or sets the station service.
        /// </summary>
        /// <value>
        /// The station service.
        /// </value>
        private IProductionStationService StationService { get; set; }

        /// <summary>
        /// Gets a list of available report types.
        /// </summary>
        /// <returns>List of report types.</returns>
        private static IEnumerable<ReportTypeModel> ReportTypes()
        {
            var list = new List<ReportTypeModel>();

            foreach (var method in typeof(ReportController).GetMethods())
            {
                var attrs = method.GetCustomAttributes(typeof(ReportMethodAttribute), true);
                if (attrs.Any())
                {
                    var attr = attrs[0] as ReportMethodAttribute;
                    list.Add(new ReportTypeModel(method.Name, attr.Name));
                }
            }

            return list;
        }
        
        /// <summary>
        /// Index view.
        /// </summary>
        /// <returns>The reports view.</returns>
        public ActionResult Index()
        {
            ViewBag.Title = "Production Reports";

            var model = new ReportSelectModel();
            model.ReportTypes = ReportTypes();
            model.Products = this.ProductService.List().OrderBy(p => p.Description).ToList();
            model.WorkAreas = this.ProductionStageService.List()
                                        .Select(p => p.WorkArea).Distinct();

            return View(model);
        }

        /// <summary>
        /// Gets the lines specific to a work area.
        /// </summary>
        /// <param name="workArea">The work area.</param>
        /// <returns>The lines options.</returns>
        public ActionResult LinesOptions(string workArea)
        {
            var lines = this.ProductionStageService.List()
                            .Where(s => s.WorkArea == workArea)
                            .Select(s => s.LineNumber)
                            .Distinct()
                            .ToList();

            var sb = new StringBuilder("<option value=''>All</option>");
            foreach (var line in lines.OrderBy(i => i))
            {
                sb.Append(string.Format("<option value='{0}'>{0}</option>", line));
            }

            return Content(sb.ToString());
        }

        /// <summary>
        /// Generates the report.
        /// </summary>
        /// <param name="reportType">Type of the report.</param>
        /// <param name="startDate">The start date.</param>
        /// <param name="endDate">The end date.</param>
        /// <param name="product">The product.</param>
        /// <param name="workArea">The work area.</param>
        /// <param name="line">The line.</param>
        /// <returns>The report view.</returns>
        public ActionResult GenerateReport(
                string reportType,
                DateTime startDate,
                DateTime endDate,
                Guid? productId,
                string workArea,
                int? line)
        {
            var model = new GenerateReportModel();
            model.StartDate = startDate;
            model.EndDate = endDate;
            model.Line = line;
            model.ProductId = productId;
            model.WorkArea = workArea;

            var method = typeof(ReportController).GetMethod(reportType);
            var ret = method.Invoke(this, new object[] { model });

            return ret as ActionResult;
        }

        /// <summary>
        /// Filters production stages by the report model.
        /// </summary>
        /// <param name="list">The list.</param>
        /// <param name="model">The model.</param>
        /// <returns>Filtered queryable.</returns>
        private IQueryable<ProductionStage> FilterStages(IQueryable<ProductionStage> list, GenerateReportModel model)
        {
            list = list.Where(s => s.TimeStamp > model.StartDate && s.TimeStamp < model.EndDate);

            if (model.ProductId.HasValue)
            {
                list = list.Where(s => s.ProductionEntry.Product.Id == model.ProductId);
            }

            if (!string.IsNullOrEmpty(model.WorkArea))
            {
                list = list.Where(s => s.WorkArea == model.WorkArea);
                if (model.Line.HasValue)
                {
                    var i = model.Line.Value;
                    list = list.Where(s => s.LineNumber == i);
                }
            }

            return list;
        }

        #region Report Action Methods

        /// <summary>
        /// Generates the first yield report.
        /// </summary>
        /// <returns>The first yield report view.</returns>
        [ReportMethod("First Yield")]
        public ActionResult FirstYield(GenerateReportModel model)
        {
            // get list of stations
            var stations = this.StationService.List().Where(s => s.StationType == "Inspection").ToList();
            var yieldModel = new FirstYieldModel();
            yieldModel.Charts = new Collection<Highcharts>();

            foreach (var station in stations.OrderBy(s => s.Identifier))
            {
                // inspection and related rework and scrap states
                var inspection = station.Identifier;
                var rework = inspection + "_REWORK";
                var reject = inspection + "_SCRAP";

                // linq to get the stages
                var list = this.FilterStages(this.ProductionStageService.List(), model)
                               .Where(s => s.Station.Identifier == rework
                                   || s.Station.Identifier == reject
                                   || s.Station.Identifier == inspection)
                               .GroupBy(s => s.Station)
                               .OrderBy(g => g.Count())
                               .Select(g => new { Name = (g.Key.StationType == "Inspection" ? "Passed" : g.Key.StationType), Y = g.Count() })
                               .ToArray();

                // get the total of "not first times"
                var bad = list.Where(a => a.Name != "Passed").Sum(a => a.Y);

                // we need to subract the number of
                // not first times from the first times
                var results = new List<object>();
                foreach (var a in list)
                {
                    if (a.Name == "Passed")
                    {
                        results.Add(new { Name = a.Name, Y = a.Y - bad });
                    }
                    else
                    {
                        results.Add(a);
                    }
                }
                
                // build chart
                var chart = ChartHelper.PieChart(
                    string.Format("{0} First Time Yield", station.Description),
                    "First Time Yield",
                    results.ToArray(),
                    station.Identifier);

                yieldModel.Charts.Add(chart);
            }

            return PartialView("FirstYield", yieldModel);
        }

        /// <summary>
        /// Generates the final yield report.
        /// </summary>
        /// <returns>The final yield report view.</returns>
        [ReportMethod("Final Yield")]
        public ActionResult FinalYield(GenerateReportModel model)
        {
            // linq to get the final yeild of good, bad, and ugly
            var list = this.FilterStages(this.ProductionStageService.List(), model)
                .Where(s => s.Station.StationType == "Scrap" || s.Station.StationType == "Complete")

PrestigeYoYo/src/Web/Views/Report/DefectCategories.cshtml
@using Prestige.ViewModels;

<script type="text/javascript">
    $(function () {
        $(".datetime-picker").datetimepicker({
            stepMinute: 15
        });
    });
</script>

<script src="../../Scripts/highcharts/js/highcharts.js" type="text/javascript"></script>

@model DotNet.Highcharts.Highcharts

@(Model)

PrestigeYoYo/src/Web/Views/Report/FinalYield.cshtml
@using Prestige.ViewModels;

<script type="text/javascript">
    $(function () {
        $(".datetime-picker").datetimepicker({
            stepMinute: 15
        });
    });
</script>

<script src="../../Scripts/highcharts/js/highcharts.js" type="text/javascript"></script>

@model DotNet.Highcharts.Highcharts

@(Model)

PrestigeYoYo/src/Web/Views/Report/FirstYield.cshtml
@using Prestige.ViewModels;
@model FirstYieldModel

<script type="text/javascript">
    $(function () {
        $(".datetime-picker").datetimepicker({
            stepMinute: 15
        });
    });
</script>

<script src="../../Scripts/highcharts/js/highcharts.js" type="text/javascript"></script>

@foreach (var chart in Model.Charts)
{
<div style="min-width:500px;width:49%;float:left;">
    @chart
</div>
}

PrestigeYoYo/src/Web/Views/Report/Index.cshtml
@using Prestige.ViewModels;
@model Prestige.ViewModels.ReportSelectModel

<!--
im thinking like
they pick their report type
they fill in the appropriate fields
start date, end date
work area, line
product type
they hit generate
and boom, its generates
-->

@Url.Script("~/Scripts/highcharts/js/highcharts.js")

<script type="text/javascript">
    $(function () {
        var defaultBackColor = $("#startDate").css("border-color");
        var defaultColor = $("#startDate").css("background-color");

        $(".datetime-picker").datetimepicker({
            stepMinute: 15
        });

        $("#workArea").change(function () {
            $("#line").load(
                "@Url.Action("LinesOptions", "Report")",
                {
                    workArea: $("#workArea").val()
                });
        });

        $("#btnGenerate").button().click(function () {
            var report = $("#reportType").val();
            var start = $("#startDate").val();
            var end = $("#endDate").val();
            var product = $("#product").val();
            var workArea = $("#workArea").val();
            var line = $("#line").val();

            var startDate = Date.parse(start);
            var endDate = Date.parse(end);

            // TODO: validate inputs
            if (!startDate) {
                $("#startDate").css("border-color", "red");
                $("#startDate").css("background-color", "#ffdddd");
                $("#startDate").attr("title", "You must enter a start date");
            } else {
                $("#startDate").css("border-color", defaultBackColor);
                $("#startDate").css("background-color", defaultColor);
                $("#startDate").attr("title", "");
            }

            if (!endDate) {
                $("#endDate").css("border-color", "red");
                $("#endDate").css("background-color", "#ffdddd");
                $("#endDate").attr("title", "You must enter an end date");
            } else {
                $("#endDate").css("border-color", defaultBackColor);
                $("#endDate").css("background-color", defaultColor);
                $("#endDate").attr("title", "");
            }

            if (startDate && endDate) {
                if (startDate < endDate) {
                    $("#startDate").css("border-color", defaultBackColor);
                    $("#startDate").css("background-color", defaultColor);
                    $("#startDate").attr("title", "");
                    $("#endDate").css("border-color", defaultBackColor);
                    $("#endDate").css("background-color", defaultColor);
                    $("#endDate").attr("title", "");

                    $("#loader").show();
                    $("#chartContainer").load(
                        "@Url.Action("GenerateReport", "Report")",
                        {
                            reportType: report,
                            startDate: start,
                            endDate: end,
                            productId: product,
                            workArea: workArea,
                            line: line
                        },
                        function () {
                            $("#loader").hide();
                        });
                } else {
                    $("#startDate").css("border-color", "red");
                    $("#startDate").css("background-color", "#ffdddd");
                    $("#startDate").attr("title", "The start date must be before the end date");
                    $("#endDate").css("border-color", "red");
                    $("#endDate").css("background-color", "#ffdddd");
                    $("#endDate").attr("title", "The end date must be before the start date");
                }
            }
        });
    });
</script>

<style type="text/css">
    .field-value
    {
        width:250px;
        margin-bottom:20px;
    }
    select.field-value
    {
        width:255px;
    }
    #fieldsContainer
    {
        vertical-align:top;
    }
    #fieldsContainer #panel
    {
        padding:30px 30px 30px 0px;
        border-right: 1px solid black;
    }
</style>

<table>
<tr>
<td id="fieldsContainer">
    <div id="panel">
        <div>
            <label for="reportType">Report Type:</label>
        </div>
        <div>
            <select name="reportType" id="reportType" class="field-value">
            @foreach (var report in Model.ReportTypes)
            {
                <option value="@report.Id">@report.Name</option>
            }
            </select>
        </div>

        <div>
            <label for="StartDate">Start Date:</label>
        </div>
        <div>
            <input name="StartDate" id="startDate" type="text" readonly="readonly" class="datetime-picker field-value" />
        </div>

        <div>
            <label for="EndDate">End Date:</label>
        </div>
        <div>
            <input name="EndDate" id="endDate" type="text" readonly="readonly" class="datetime-picker field-value" />
        </div>

        <div>
            <label for="product">Product:</label>
        </div>
        <div>
            <select name="product" id="product" class="field-value">
                <option value="">All</option>
            @foreach (var product in Model.Products)
            {
                <option value="@product.Id.ToString()">@product.Description - @product.Colour (@product.SKU)</option>
            }
            </select>
        </div>

        <div>
            <label for="workArea">Work Area:</label>
        </div>
        <div>
            <select name="workArea" id="workArea" class="field-value">
                <option value="">All</option>
            @foreach (var area in Model.WorkAreas)
            {
                <option value="@area">@area</option>
            }
            </select>
        </div>

        <div>
            <label for="line">Line:</label>
        </div>
        <div>
            <select name="line" id="line" class="field-value">
                <option value="">All</option>
            </select>
        </div>

        <div>
            <button id="btnGenerate">Generate</button>
            <img id="loader" alt="Loading..." src="@Url.Content("~/Content/images/ajax-loader.gif")" style="vertical-align:bottom;display:none;" />
        </div>
    </div>
</td>

<td id="chartContainer" style="width:100%;">
</td>

</tr>
</table>